<?php
// vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 encoding=utf-8 fdm=marker :
// {{{ Licence
// +--------------------------------------------------------------------------+
// | Text_Normalize                                                           |
// +--------------------------------------------------------------------------+
// | Copyright (C) 2008 Nicolas Thouvenin                                     |
// +--------------------------------------------------------------------------+
// | This library is free software; you can redistribute it and/or            |
// | modify it under the terms of the GNU General Public License              |
// | as published by the Free Software Foundation; either  version 2          |
// | of the License, or (at your option) any later version.                   |
// |                                                                          |
// | This program is distributed in the hope that it will be useful,          |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         |
// | General Public License for more details.                                 |
// |                                                                          |
// | You should have received a copy of the GNU General Public License        |
// | along with this library; if not, write to the Free Software              |
// | Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  |
// +--------------------------------------------------------------------------+
// }}}

/**
 * @category  Text
 * @packageText_Normalize
 * @author Nicolas Thouvenin <nthouvenin@gmail.com>
 * @copyright 2008 Nicolas Thouvenin
 * @licensehttp://opensource.org/licenses/lgpl-license.php LGPL
 * @versionSVN: $Id$
 * @linkhttp://www.touv.fr/spip.php?id_article=145
 */
require_once 'Text/Normalize/Stemming.php';


/**
 * Classe pour garder uniquement le racine des mots
 *
 * @category  Text
 * @packageText_Normalize
 * @author Nicolas Thouvenin <nthouvenin@gmail.com>
 * @copyright 2008 Nicolas Thouvenin
 * @licensehttp://opensource.org/licenses/lgpl-license.php LGPL
 * @linkhttp://www.touv.fr/spip.php?id_article=145
 */
class Text_Normalize_Stemming_Fra extends Text_Normalize_Stemming
{
    static $ListAUX_AUX_FR =array(
        "chaux",
        "apparaux",
        "attifiaux",
        "bedaux",
        "bestiaux",
        "faux",
        "taux"
    );
    static $ListEAUX_EAUX_FR = array(
        "bordeaux",
        "champeaux"
    );
    static $ListAUX_AU_FR = array(
        "affutiaux",
        "agiaux",
        "aloyaux",
        "aveiniaux",
        "boyaux",
        "burgaux",
        "carpiaux",
        "coyiaux",
        "fabliaux",
        "feldgraux",
        "fléaux",
        "gluaux",
        "goyaux",
        "graux",
        "gruaux",
        "hoyaux",
        "joyaux",
        "massiaux",
        "nobliaux",
        "noyaux",
        "pilaux",
        "préaux",
        "touchaux",
        "tufaux",
        "tuyaux",
        "verdiaux",
        "ypréaux",
        "etaux"
    );
    static $ListAUX_AIL_FR = array(
        "aspiraux",
        "baux",
        "coraux",
        "émaux",
        "fermaux",
        "soupiraux",
        "travaux",
        "vitraux"
    );
    static $ListUX_U_FR = array(
        "aleux",
        "alleux",
        "arrière-neveux",
        "arrière-petits-neveux",
        "aveux",
        "bateaux-feux",
        "bijoux",
        "boutefeux",
        "cailloux",
        "camaieux",
        "cayeux",
        "calleux",
        "chefs-lieux",
        "cheveux",
        "choux",
        "contre-feux",
        "couvre-feux",
        "demi-aveux",
        "demi-dieux",
        "dieux",
        "désaveux",
        "enfeux",
        "enjeu",
        "essieux",
        "fesse-mathieux",
        "feux",
        "francs-aleux",
        "francs-alleux",
        "garde-feux",
        "genoux",
        "hiboux",
        "hébreux",
        "jeux",
        "joujoux",
        "lieux",
        "milieux",
        "moyeux",
        "neveux",
        "non-lieux",
        "part-feux",
        "petits-neveux",
        "pieux",
        "poux",
        "tonlieux",
        "voeux",
        "épieux"
    );
    static $ListS_S_FR = array(
        "ados",
        "abscons",
        "accès",
        "acens",
        "aegilops",
        "agets",
        "agrippe-rossignols",
        "albatros",
        "albinos",
        "alentours",
        "alios",
        "amnios",
        "anacampséros",
        "anchilops",
        "anticorps",
        "antigène-anticorps",
        "anti-chars",
        "apios",
        "arrière-corps",
        "arrière-pays",
        "arrière-petits-enfants",
        "ars",
        "atropos",
        "aubours",
        "aurochs",
        "autoanticorps",
        "avant-corps",
        "avant-printemps",
        "avers",
        "bas",
        "basileus",
        "beaux-arts",
        "beaux-fils",
        "beaux-parents",
        "beau-fils",
        "benthos",
        "biceps",
        "bien-fonds",
        "bitos",
        "blaps",
        "blockhaus",
        "boute-dehors",
        "boute-hors",
        "bout-dehors",
        "burnous",
        "byblos",
        "calvados",
        "campos",
        "casse-pieds",
        "cens",
        "cers",
        "chaos",
        "chauffe-pieds",
        "chips",
        "clebs",
        "clos",
        "coccinelliens",
        "concours",
        "confins",
        "contrepoids",
        "contresens",
        "contretemps",
        "convers",
        "corps",
        "cosmos",
        "cotylausauriens",
        "couche-dehors",
        "coulommiers",
        "cours",
        "couscous",
        "couvre-pieds",
        "crapulos",
        "creps",
        "crocodiliens",
        "cure-dents",
        "cynips",
        "dedans",
        "dehors",
        "deliriumtremens",
        "dessous",
        "deux-points",
        "discours",
        "dos",
        "dromos",
        "débours",
        "décours",
        "défens",
        "dépens",
        "dévers",
        "encens",
        "enclos",
        "endos",
        "entrelacs",
        "entremets",
        "entrevous",
        "envers",
        "environs",
        "errements",
        "ers",
        "essuie-mains",
        "euniciens",
        "extrados",
        "fils",
        "flueurs",
        "fonts",
        "forceps",
        "garde-à-vous",
        "garde-corps",
        "garde-temps",
        "gars",
        "gens",
        "grabons",
        "grands-parents",
        "gravats",
        "greubons",
        "gros",
        "guets-apens",
        "guet-apens",
        "haut-le-corps",
        "hendiadys",
        "hominiens",
        "hustings",
        "héros",
        "ichtys",
        "intrados",
        "ithos",
        "jars",
        "jodhpurs",
        "jonchets",
        "justaucorps",
        "kleps",
        "knickerbockers",
        "koumys",
        "kouros",
        "labadens",
        "lance-engins",
        "laps",
        "lave-mains",
        "leggins",
        "legs",
        "libripens",
        "links",
        "lods",
        "logos",
        "los",
        "lys",
        "lémuriens",
        "mamours",
        "marais",
        "mars",
        "maths",
        "mets",
        "mire-oeufs",
        "mi-temps",
        "moeurs",
        "monte-plats",
        "mors",
        "mort-aux-rats",
        "mouche-bouchons",
        "mérinos",
        "naos",
        "non-sens",
        "oaristys",
        "obvers",
        "oeils",
        "ophrys","abscons",
        "ophrys",
        "opilions",
        "orléans",
        "ossements",
        "os",
        "ours",
        "parados",
        "parcours",
        "paros",
        "passe-temps",
        "passe-velours",
        "pathos",
        "pays","acens",
        "pays",
        "perfringens",
        "pervers",
        "petits-enfants",
        "petits-fils",
        "petit-fils",
        "pithiviers",
        "pleinstemps",
        "pleins-temps",
        "pleintemps",
        "plein-temps",
        "poids",
        "porte-avions",
        "porte-billets",
        "porte-documents",
        "porte-liqueurs",
        "pouls",
        "pourparlers",
        "presse-papiers",
        "princeps",
        "printemps",
        "promérops",
        "pronaos",
        "propos",
        "proteus",
        "prélegs",
        "ptérosauriens",
        "puits",
        "péplos",
        "quadriceps",
        "quatretemps",
        "quatre-quarts",
        "quatre-saisons",
        "quatre-temps",
        "rams",
        "rebours",
        "recors",
        "recours",
        "regros",
        "relaps",
        "remords",
        "remous",
        "rendez-vous",
        "repos",
        "reps",
        "rets",
        "revers",
        "rhinocéros",
        "rillons",
        "rince-doigts",
        "roberts",
        "rollmops",
        "ros",
        "roustons",
        "répons",
        "saros",
        "schnaps",
        "secours",
        "sens",
        "seps",
        "serre-fils",
        "siemens",
        "siréniens",
        "skungs",
        "spéculos",
        "spéos",
        "stamnos",
        "strychnos",
        "suros",
        "suspens",
        "sélaciens",
        "tchervonets",
        "temps",
        "température-temps",
        "thermos",
        "tholos",
        "thrips",
        "tiers",
        "tors",
        "tournedos",
        "travails",
        "travers",
        "triceps",
        "triceratops",
        "tricotets",
        "trois-mouts",
        "trois-quarts",
        "tréfonds",
        "tuniciers",
        "turneps",
        "téléostéens",
        "téménos",
        "tétanos",
        "univers",
        "uraeus",
        "va-nu-pieds",
        "velours",
        "vermidiens",
        "vers",
        "vivats",
        "williams",
        "écours",
        "éthiops",
        "éthiops"
    );
    static $ListAS_AS_FR = array(
        "abas",
        "abdalas",
        "abras",
        "abraxas",
        "acomas",
        "alcarazas",
        "amas",
        "ambesas",
        "ananas",
        "androdamas",
        "appas",
        "asclépias",
        "atlas",
        "bas",
        "baaras",
        "balénas",
        "bolas",
        "bourras",
        "branlebas",
        "bras",
        "bédigas",
        "cabas",
        "cadenas",
        "camocas",
        "canevas",
        "cannelas",
        "carabas",
        "catoblépas",
        "cervelas",
        "charabias",
        "chas",
        "chasselas",
        "choucas",
        "christmas",
        "compas",
        "contrebas",
        "coutelas",
        "cycas",
        "cyclas",
        "damaras",
        "damas",
        "débarras",
        "dégras",
        "embarras",
        "encas",
        "fatras",
        "fracas",
        "frimas",
        "galetas",
        "galimatias",
        "gingas",
        "glas",
        "gras",
        "hamadryas",
        "haras",
        "hypocras",
        "jaconas",
        "jas",
        "judas",
        "lampas",
        "las",
        "lias",
        "madras",
        "matelas",
        "matras",
        "millas",
        "ninas",
        "pancréas",
        "pas",
        "papas",
        "pataras",
        "paterfamilias",
        "plexiglas",
        "ploutras",
        "pourchas",
        "pourounas",
        "psoas",
        "poutiras",
        "pétras",
        "radiocompas",
        "ramas",
        "ras",
        "rebras",
        "repas",
        "sassafras",
        "soulas",
        "taffetas",
        "tas",
        "thomas",
        "tracas",
        "trias",
        "trépas",
        "tétras",
        "upas",
        "vasistas",
        "verglas",
        "vindas",
        "xiphias",
        "échalas"
    );
    static $ListIS_I_FR = array(
        "abois",
        "abris",
        "abrutis",
        "accourcis",
        "acouchis",
        "adelaizis",
        "adoucis",
        "affaiblis",
        "affranchis",
        "agamis",
        "agatis",
        "aguerris",
        "aguis",
        "ahuris",
        "aigris",
        "aillolis",
        "alcalis",
        "alfaquis",
        "algalis",
        "alibis",
        "alizaris",
        "alkalis",
        "allouvis",
        "allumis",
        "allégis",
        "alois",
        "alouchis",
        "amatis",
        "amincis",
        "amis",
        "ammis",
        "amortis",
        "amphigouris",
        "anoblis",
        "antaris",
        "apis",
        "apprentis",
        "appuis",
        "après-midis",
        "arbis",
        "argalis",
        "arrois",
        "arrondis",
        "assaillis",
        "assakis",
        "assoupis",
        "assujettis",
        "astis",
        "attendris",
        "autos-taxis",
        "avant-midis",
        "allolis",
        "babis",
        "baillis",
        "bais",
        "balais",
        "balis",
        "bannis",
        "baris",
        "beffrois",
        "bengalis",
        "bibis",
        "bigoudis",
        "bikinis",
        "bimbachis",
        "biribis",
        "bistouris",
        "bleuis",
        "bonis",
        "bostangis",
        "bouffis",
        "bouillis",
        "bouis-bouis",
        "boulevaris",
        "boulvaris",
        "brais",
        "brocolis",
        "brouillaminis",
        "brunis",
        "boubis",
        "boutis",
        "bénis",
        "cabiais",
        "cabris",
        "cadis",
        "cafedjis",
        "cagibis",
        "canaris",
        "cannellonis",
        "carrois",
        "carvis",
        "catis",
        "chais",
        "champis",
        "chancis",
        "charivaris",
        "charrois",
        "chiantis",
        "chichis",
        "chtimis",
        "chéris",
        "coatis",
        "colibris",
        "confettis",
        "convertis",
        "convois",
        "corroboris",
        "corrois",
        "courliris",
        "cricris",
        "cris",
        "crépis",
        "cutis",
        "céleris",
        "dallris",
        "demis",
        "droschkis",
        "droskis",
        "duodis",
        "déblais",
        "débouillis",
        "décadis",
        "décris",
        "défis",
        "dégourdis",
        "délais",
        "démentis",
        "dénis",
        "désarrois",
        "désennuis",
        "efendis",
        "effendis",
        "effrois",
        "embrouillaminis",
        "emplois",
        "engourdis",
        "engris",
        "ennemis",
        "ennuis",
        "envois",
        "essais",
        "etablis",
        "extravertis",
        "extrovertis",
        "faillis",
        "favoris",
        "fieris",
        "fifis",
        "fourbis",
        "fourmis",
        "frichtis",
        "garnis",
        "geais",
        "gluis",
        "gnocchis",
        "goumis",
        "gourbis",
        "graffitis",
        "grigris",
        "grisbis",
        "gris-gris",
        "guaranis",
        "guilleris",
        "guimbris",
        "guis",
        "gummis",
        "génipis",
        "génépis",
        "hadjis",
        "hallalis",
        "harkis",
        "hindis",
        "hindoustanis",
        "houris",
        "hourvaris",
        "indéfinis",
        "infinis",
        "insoucis",
        "interrois",
        "invertis",
        "jaborandis",
        "jeudis",
        "jokaris",
        "jourd' huis",
        "kabukis",
        "kadis",
        "kakis",
        "kalis",
        "kamichis",
        "kamis",
        "kauris",
        "khis",
        "kiwis",
        "kolinskis",
        "ksis",
        "képis",
        "labris",
        "lais",
        "lapillis",
        "largonjis",
        "latakis",
        "lazzis",
        "letchis",
        "lis",
        "litchis",
        "lois",
        "loreleis",
        "loris",
        "lundis",
        "macaronis",
        "mahdis",
        "mahoganis",
        "mais",
        "makis",
        "mamamouchis",
        "maoris",
        "mardis",
        "maris",
        "marlis",
        "mercantis",
        "mercis",
        "mercredis",
        "métis",
        "midis",
        "mimis",
        "minerais",
        "minis",
        "mistigris",
        "moisis",
        "monokinis",
        "muftis",
        "muphtis",
        "muscaris",
        "méchouis",
        "méharis",
        "mésemplois",
        "nabis",
        "nantis",
        "nazis",
        "nedjis",
        "nervis",
        "niaoulis",
        "nonidis",
        "nérolis",
        "obis",
        "octidis",
        "octrois",
        "okapis",
        "orfrois",
        "organdis",
        "oublis",
        "ouistitis",
        "oustachis",
        "pacfis",
        "palefrois",
        "palis",
        "papegais",
        "paris",
        "parois",
        "parolis",
        "parsis",
        "partis",
        "patchoulis",
        "peccavis",
        "pehlvis",
        "pelotaris",
        "pendjabis",
        "pervertis",
        "phis",
        "piloris",
        "pipis",
        "plis",
        "polis",
        "pots-pourris",
        "pourris",
        "pourvois",
        "psis",
        "pécaris",
        "péris",
        "quais",
        "quartidis",
        "quasis",
        "quintidis",
        "quiquis",
        "rabbis",
        "raccourcis",
        "rais",
        "rakis",
        "ralentis",
        "ramis",
        "ramollis",
        "ranis",
        "rastafaris",
        "raviolis",
        "ravis",
        "refroidis",
        "remblais",
        "remplis",
        "remplois",
        "renvis",
        "renvois",
        "repentis",
        "replis",
        "ressuis",
        "richis",
        "rififis",
        "riquiquis",
        "rishis",
        "rois",
        "rôtis",
        "rouchis",
        "rouis",
        "roumis",
        "roussis",
        "récris",
        "réemplois",
        "safaris",
        "sakis",
        "salamis",
        "samedis",
        "sampis",
        "sapellis",
        "saris",
        "satis",
        "sallmiris",
        "scaferlatis",
        "sefardis",
        "septidis",
        "sertis",
        "sextidis",
        "sidis",
        "similis",
        "sirlis",
        "sirtakis",
        "skis",
        "sloughis",
        "somalis",
        "sophis",
        "souahélis",
        "soucis",
        "soufis",
        "sous-emplois",
        "spaghettis",
        "spahis",
        "spermacetis",
        "suivis",
        "suris",
        "surmois",
        "swahilis",
        "soutis",
        "sénégalis",
        "tabis",
        "tassilis",
        "tatamis",
        "taxis",
        "terris",
        "thlaspis",
        "titis",
        "tournois",
        "transfinis",
        "travestis",
        "tridis",
        "tripolis",
        "tris",
        "tsunamis",
        "téléskis",
        "téocallis",
        "unis",
        "vendredis",
        "venturis",
        "vice-baillis",
        "vice-rois",
        "virelais",
        "vomis",
        "vrais",
        "vélanis",
        "wapitis",
        "wiskis",
        "yetis",
        "yogis",
        "zanis",
        "zannis",
        "zanzis",
        "zingaris",
        "zizis",
        "zombis",
        "zébis",
        "écofrois",
        "élémis",
        "émeris",
        "émois",
        "épais",
        "épis",
        "épois",
        "époutis",
        "établis",
        "étais",
        "étambrais",
        "étuis"
    );

    static $ListUS_U_FR = array(
        "absolus",
        "accrus",
        "apercus",
        "andalous",
        "barbus",
        "bienvenus",
        "bossus",
        "brus",
        "bécharus",
        "cartahus",
        "chevelus",
        "codétenus",
        "continus",
        "copahus",
        "cossus",
        "courts-pendus",
        "crus",
        "discontinus",
        "dévolus",
        "feuillus",
        "fichus",
        "fétus",
        "glus",
        "goglus",
        "gras-fondus",
        "hotus",
        "hurluberlus",
        "hypertendus",
        "hypotendus",
        "impromptus",
        "imprévus",
        "inattendus",
        "inconnus",
        "individus",
        "jabirus",
        "lardus",
        "locdus",
        "loquedus",
        "lustucrus",
        "malentendus",
        "malotrus",
        "malvenus",
        "menus",
        "merlus",
        "moins-percus",
        "mus",
        "nus",
        "poilus",
        "pointus",
        "pécus",
        "rendus",
        "rus",
        "résidus",
        "superflus",
        "tard-venus",
        "tissus",
        "tohu-bohus",
        "tolus",
        "tribus",
        "trop-percus",
        "tutus",
        "tétus",
        "urubus",
        "vertus",
        "zébus",
        "écus"
    );


    // {{{ tranform
    /**
     * supprime ...
     *
     * @param string $str
     *
     * @return string
     */
    public function transform($str)
    {
        $word = array();
        $regles = array();
        $word_array = explode (" ",$str);

        foreach ($word_array as  $value) {

            $char = strtolower(substr ($value ,-1 ));

            if (strlen ($value) <= 2 ) {
                $word[] = $value;
                continue;
            }

            if ($char != "x" and $char != "s") {
                $word[] = $value;
                continue;
            }

            if( $char == 'x') {

                if (in_array (strtolower ($value), self::$ListEAUX_EAUX_FR)) {
                    $word[] = $value;
                    $regles[] = 'frx1';
                }

                elseif ((strcasecmp ("eaux",substr($value,-4)) == 0 )) {
                    $word[] = preg_replace(",(eau)x$,i","\\1",$value);
                    $regles[] = 'frx2';
                }

                elseif (in_array (strtolower ($value), self::$ListAUX_AU_FR)) {
                    $word[] = preg_replace(",(au)x$,i","\\1",$value);
                    $regles[] = 'frx3';
                }

                elseif (in_array (strtolower ($value),self::$ListAUX_AUX_FR)) {
                    $word[] = $value;
                    $regles[] = 'frx4';
                }

                elseif (in_array (strtolower ($value),self::$ListAUX_AIL_FR)) {
                    $value = preg_replace (",aux$,", "ail", $value, 1);
                    $word[] = preg_replace (",AUX$,", "AIL", $value, 1);
                    $regles[] = 'frx5';

                }

                elseif  (( strcasecmp ("aux",substr($value,-3)== 0)and strlen($value)> 3))  {
                    $value = preg_replace (",aux$,", "al",$value, 1);
                    $word[] = preg_replace (",AUX$,","AL",$value, 1 );
                    $regles[] = 'frx6';
                }

                elseif (in_array (strtolower ($value),self::$ListUX_U_FR)) {
                    $value = preg_replace (",ux$,","u",$value, 1);
                    $word[] = preg_replace (",UX$,","U",$value, 1);
                    $regles[] = 'frx7';
                }
                else {
                    $word[]= $value ;

                }

            }



            if ($char == 's') {

                if (in_array (strtolower ($value),self::$ListAS_AS_FR)) {
                    $word[] = $value;
                    $regles[] = 'frs1';
                }

                elseif (in_array (strtolower($value),self::$ListUS_U_FR)) {
                    $value = preg_replace ("`us$`","u",$value,1);
                    $word[] = preg_replace ("`US$`","U",$value,1);
                    $regles[] = 'frs2';
                }

                elseif (strcasecmp ("us" ,substr ($value,-2))== 0) {
                    $value = preg_replace ("`us$`","us",$value,1);
                    $word[] = preg_replace ("`US$`","US",$value,1);
                    $regles[] = 'frs3';
                }

                elseif (in_array (strtolower ($value) ,self::$ListIS_I_FR)) {
                    $value = preg_replace (",is$,","i",$value,1);
                    $word[] = preg_replace (",IS$,","I",$value,1);
                    $regles[] = 'frs4';
                }

                elseif (strcasecmp ("is", substr ($value,-2))== 0) {
                    $value = preg_replace (",is$,","is",$value,1);
                    $word[] = preg_replace (",IS$,","IS",$value,1);
                    $regles[] = 'frs5';
                }

                elseif (in_array  (strtolower ($value),self::$ListS_S_FR)) {
                    $word[] = $value;
                    $regles[] = 'frs6';
                }

                elseif ( strcasecmp ("s", substr ($value,-1)) == 0) {
                    $value = preg_replace (",s$,","",$value, 1);
                    $word[] = preg_replace (",S$,","",$value, 1);
                    $regles[] = 'frs7';
                }
            }

        }/* fin boucle */

        return implode(' ', $word);
    }
    // }}}
}
