<?php
// vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 encoding=utf-8 fdm=marker :
// {{{ Licence
// +--------------------------------------------------------------------------+
// | Text_Normalize                                                           |
// +--------------------------------------------------------------------------+
// | Copyright (C) 2008 Nicolas Thouvenin                                     |
// +--------------------------------------------------------------------------+
// | This library is free software; you can redistribute it and/or            |
// | modify it under the terms of the GNU General Public License              |
// | as published by the Free Software Foundation; either  version 2          |
// | of the License, or (at your option) any later version.                   |
// |                                                                          |
// | This program is distributed in the hope that it will be useful,          |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of           |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         |
// | General Public License for more details.                                 |
// |                                                                          |
// | You should have received a copy of the GNU General Public License        |
// | along with this library; if not, write to the Free Software              |
// | Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA  |
// +--------------------------------------------------------------------------+
// }}}

/**
 * @category  Text
 * @package   Text_Normalize
 * @author    Nicolas Thouvenin <nthouvenin@gmail.com>
 * @copyright 2008 Nicolas Thouvenin
 * @license   http://opensource.org/licenses/lgpl-license.php LGPL
 * @version   SVN: $Id$
 * @link      http://www.touv.fr/spip.php?id_article=145
 */

require_once 'Text/Normalize/Stopwords.php';

/**
 * Classe pour supprimer les mots vides
 *
 * @category  Text
 * @package   Text_Normalize
 * @author    Nicolas Thouvenin <nthouvenin@gmail.com>
 * @copyright 2008 Nicolas Thouvenin
 * @license   http://opensource.org/licenses/lgpl-license.php LGPL
 * @link      http://www.touv.fr/spip.php?id_article=145
 */
class Text_Normalize_Stopwords_Fra extends Text_Normalize_Stopwords
{
    public static $data = array(
        ' afin ',
        ' ailleurs ',
        ' alentour ',
        ' alors ',
        ' aprés ',
        ' apres ',
        ' assez ',
        ' aucun ',
        ' aucune ',
        ' aujourd\'hui ',
        ' auparavant ',
        ' auprés ',
        ' aupres ',
        ' auquel ',
        ' auraient ',
        ' aurait ',
        ' aussi ',
        ' aussitôt ',
        ' aussitot ',
        ' autant ',
        ' autour ',
        ' autrefois ',
        ' autres ',
        ' auxquelles ',
        ' auxquels ',
        ' avaient ',
        ' avait ',
        ' avec ',
        ' beaucoup ',
        ' bientôt ',
        ' bientot ',
        ' but ',
        ' car ',
        ' ceci ',
        ' celle ',
        ' celles ',
        ' celui ',
        ' cependant ',
        ' certain ',
        ' certaines ',
        ' ces ',
        ' cet ',
        ' cette ',
        ' ceux ',
        ' chacun ',
        ' chacune ',
        ' chaque ',
        ' chez ',
        ' cind ',
        ' combien ',
        ' comme ',
        ' comment ',
        ' concernant ',
        ' c\'est ',
        ' c\'était ',
        ' c\'etait ',
        ' dans ',
        ' debout ',
        ' delà ',
        ' dela ',
        ' depuis ',
        ' dernier ',
        ' derrière ',
        ' derriere ',
        ' des ',
        ' desquelles ',
        ' desquels ',
        ' dessous ',
        ' dessus ',
        ' deux ',
        ' devant ',
        ' devra ',
        ' devront ',
        ' dis ',
        ' divers ',
        ' diverse ',
        ' diverses ',
        ' dois ',
        ' doit ',
        ' doivent ',
        ' donc ',
        ' dont ',
        ' dorénavant ',
        ' dorenavant ',
        ' duquel ',
        ' durant ',
        ' déjà ',
        ' deja ',
        ' désormais ',
        ' desormais ',
        ' dès ',
        ' des ',
        ' elle ',
        ' elles ',
        ' enfin ',
        ' envers ',
        ' environ ',
        ' etc ',
        ' eux ',
        ' excepté ',
        ' excepte ',
        ' fais ',
        ' faut ',
        ' fois ',
        ' font ',
        ' guère ',
        ' guere ',
        ' hormis ',
        ' hors ',
        ' huit ',
        ' ils ',
        ' jamais ',
        ' jusque ',
        ' jusqu\'à ',
        ' jusqu\'a ',
        ' j\'ai ',
        ' laquelle ',
        ' lequel ',
        ' lesquelles ',
        ' lesquels ',
        ' leur ',
        ' leurs ',
        ' loin ',
        ' lointain ',
        ' longtemps ',
        ' lors ',
        ' lorsque ',
        ' lui ',
        ' là ',
        ' maintenant ',
        ' mais ',
        ' malgré ',
        ' malgre ',
        ' mien ',
        ' mienne ',
        ' miennes ',
        ' miens ',
        ' mieux ',
        ' moins ',
        ' mon ',
        ' moyennant ',
        ' mêmes ',
        ' memes ',
        ' n ',
        ' ne  ',
        ' neuf ',
        ' notre ',
        ' nul ',
        ' nulle ',
        ' néanmoins ',
        ' neanmoins ',
        ' nôtre ',
        ' notre ',
        ' nôtres ',
        ' notres ',
        ' outre ',
        ' où ',
        ' parce ',
        ' pareil ',
        ' pareille ',
        ' parfois ',
        ' parmi ',
        ' partant ',
        ' partout ',
        ' pendant ',
        ' peut ',
        ' peux ',
        ' pis ',
        ' plupart ',
        ' plusieurs ',
        ' plutôt ',
        ' plutot ',
        ' pour ',
        ' pourquoi ',
        ' pourtant ',
        ' pourvu ',
        ' prochain ',
        ' prochaine ',
        ' prochaines ',
        ' prochains ',
        ' près ',
        ' pres ',
        ' puis ',
        ' puisque ',
        ' qu ',
        ' quand ',
        ' quasiment ',
        ' que ',
        ' quel ',
        ' quelconque ',
        ' quelle ',
        ' quelles ',
        ' quelque ',
        ' quelquefois ',
        ' quelques ',
        ' quelqu\'un ',
        ' quels ',
        ' qui ',
        ' quiconque ',
        ' quoi ',
        ' quoique ',
        ' rarement ',
        ' sans ',
        ' sauf ',
        ' selon ',
        ' seront ',
        ' ses ',
        ' si ',
        ' sien ',
        ' siennes ',
        ' siens ',
        ' sinon ',
        ' sitôt ',
        ' sitot ',
        ' soit ',
        ' sommes ',
        ' sont ',
        ' sorte ',
        ' souvent  ',
        ' suis ',
        ' suivant ',
        ' surtout ',
        ' sûr ',
        ' tandis ',
        ' telle ',
        ' tellement ',
        ' tien ',
        ' tienne ',
        ' tiennes ',
        ' tiens ',
        ' toi ',
        ' toujours ',
        ' toute ',
        ' toutefois ',
        ' toutes ',
        ' très ',
        ' tres ',
        ' uns ',
        ' veulent ',
        ' veut ',
        ' voici ',
        ' voilà ',
        ' voila ',
        ' voir ',
        ' votre ',
        ' voudraient ',
        ' voudrais ',
        ' vouloir ',
        ' vous ',
        ' vu ',
        ' vôtre ',
        ' votre ',
        ' vôtres ',
        ' votres ',
        ' ça ',
        ' étaient ',
        ' etaient ',
        ' étais ',
        ' etais ',
        ' était ',
        ' etait ',
        ' étiez ',
        ' etiez ',
        ' étions ',
        ' etions ',
        ' été ',
        ' ete ',
        ' êtes ',
        ' etes ',
        ' être ',
        ' etre ',
    );
    // {{{ transform
    /**
     * supprime les mots vides
     *
     * @param string $str
     *
     * @return string
     */
    public function transform($str)
    {
        return str_replace(self::$data, ' ', ' '.$str.' ');
    }
    // }}}

}
